<?xml version="1.0"?>

<robot name="sam_bot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="inertial_macros.xacro"/>

    <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
    </material>

    <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
    </material>

        <!-- Robot Base -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="Cyan"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
    
        <xacro:base_inertia m="8" d="${base_length}" w="${base_width}" h="${base_height}"/>
    </link>

    <link name="front_caster">
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
            </geometry>
     
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="1.57 0 0"/>
            <geometry>
                <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
            </geometry>
        </collision>
        <xacro:caster_inertia m="10.05" r="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
    </link>

    <joint name="caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_caster"/>
        <origin xyz="${caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/>
    </joint>

    <!-- cylinder on robot  -->
    <link name="cylinder">
        <visual>
            <geometry>
                <cylinder radius="${cylinder_raduis}" length="${cylinder_height}"/>
            </geometry>
            <material name="Cyan"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${cylinder_raduis}" length="${cylinder_height}"/>
            </geometry>
        </collision>
        <xacro:cylinder_a m="0.01" r="${cylinder_raduis}" h="${cylinder_height}"/>
    </link>

    <joint name="cylinder_joint" type="fixed">
        <parent link="base_link"/>
        <child link="cylinder"/>
        <origin xyz="${cylinder_xoff} 0.0 ${base_height/2 +cylinder_zoff}" rpy="0 0 0"/>
    </joint>


    <!-- <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 ${(wheel_zoff+wheel_radius)}" rpy="0 0 0"/>
    </joint> -->

    <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}_link">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="Gray"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>

            <xacro:cylinder_inertia m="1" r="${wheel_radius}" h="${wheel_width}"/>
        </link>

        <joint name="${prefix}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_link"/>
            <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*wheel_ygap} ${-wheel_zoff}" rpy="0 0 0"/>
            <!-- <limit upper="3.1415" lower="-3.1415" effort="30" velocity="5.0"/> -->
            <!-- <limit effort="${effort}" velocity="${velocity}" lower="${lower}" upper="${upper}"/> -->
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1" />
    <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1" />

</robot>